API <http://127.0.0.1:8000/users/> TEST Bug Fixed: _ <AttributeError: 'str' object has no attribute 'credentials'.> passing <credential> and trying to access<credential.credentials> which is not there